-- SOLO LECTURA. Exportar la única cuadrícula como 04_catalogos.csv.
-- No incluye personas. FEC_CREACION/FEC_ACTUALIZACION no son fechas del calendario académico.
SELECT N'dbo' AS source_schema, N'DIM_PERIODO' AS catalog,
       CONVERT(nvarchar(100),p.ID_PERIODO_ACADEMICO) AS source_code,
       CONVERT(nvarchar(300),p.DES_PERIODO_ACADEMICO) AS source_label,
       CONVERT(nvarchar(100),p.TIP_PERIODO) AS additional_value
FROM dbo.DIM_PERIODO AS p
UNION ALL
SELECT N'IC',N'DIM_PERIODOACAD',CONVERT(nvarchar(100),p.ID_PERIODO),
       CONVERT(nvarchar(300),p.DESC_PERIODO),CONVERT(nvarchar(100),p.COD_PERIODO)
FROM IC.DIM_PERIODOACAD AS p
UNION ALL
SELECT N'dbo',N'DIM_CAMPUS',CONVERT(nvarchar(100),c.ID_CAMPUS),CONVERT(nvarchar(300),c.DES_CAMPUS),NULL
FROM dbo.DIM_CAMPUS AS c
UNION ALL
SELECT N'dbo',N'DIM_MODALIDAD',CONVERT(nvarchar(100),m.ID_MODALIDAD),CONVERT(nvarchar(300),m.DES_MODALIDAD),CONVERT(nvarchar(100),m.TIP_MODALIDAD)
FROM dbo.DIM_MODALIDAD AS m
UNION ALL
SELECT N'PSG',N'DIM_MODALIDAD',CONVERT(nvarchar(100),m.ID_MODALIDAD),CONVERT(nvarchar(300),m.DES_MODALIDAD),NULL
FROM PSG.DIM_MODALIDAD AS m
UNION ALL
SELECT N'IC',N'DIM_MODALIDAD',CONVERT(nvarchar(100),m.ID_MODALIDAD),CONVERT(nvarchar(300),m.DESC_MODALIDAD),NULL
FROM IC.DIM_MODALIDAD AS m
UNION ALL
SELECT N'dbo',N'DIM_ESTADO',CONVERT(nvarchar(100),e.ID_ESTADO),CONVERT(nvarchar(300),e.DES_ESTADO),NULL
FROM dbo.DIM_ESTADO AS e
UNION ALL
SELECT N'PSG',N'DIM_ESTADO',CONVERT(nvarchar(100),e.ID_ESTADO),CONVERT(nvarchar(300),e.DES_ESTADO),NULL
FROM PSG.DIM_ESTADO AS e
UNION ALL
SELECT N'IC',N'DIM_ESTADO',CONVERT(nvarchar(100),e.ID_ESTADO),CONVERT(nvarchar(300),e.DESC_ESTADO),CONVERT(nvarchar(100),e.COD_ESTADO)
FROM IC.DIM_ESTADO AS e
UNION ALL
SELECT N'dbo',N'DIM_ESTADO_TIPO_ESTUDIANTE',CONVERT(nvarchar(100),e.ID_ESTADO_TIPO_ESTUDIANTE),
       CONVERT(nvarchar(300),e.DES_TIPO_ESTUDIANTE),NULL
FROM dbo.DIM_ESTADO_TIPO_ESTUDIANTE AS e
UNION ALL
-- Estados del funnel comercial de Continua; no asumir que representan egreso académico.
SELECT N'EDC',N'DIM_ESTADO_FUNNEL',CONVERT(nvarchar(100),e.ID_SUBESTADO),
       CONVERT(nvarchar(300),e.DES_SUBESTADO),CONVERT(nvarchar(100),e.DES_ESTADO)
FROM EDC.DIM_ESTADO_FUNNEL AS e
ORDER BY source_schema,catalog,source_code;
